/**
 * Como declarar Variáveis
 * 
 * ° Var (Valor mutável, CamelCase)
 *  Variável que pode ter seu valor alterado durante o código;
 * 
 * ° Val (valor imutável, CamelCase): 
 *  Variável que terá somente o valor atribuído (simalar ao final em Java);
 * 
 * ° Const Val (Valor imutável, SNAKE_CASE): 
 *  Constante cujo valor é atribuído durante compilação.
 * 
 */


//função principal
fun main() {
    val maxAGE = 68
    var currentAge:Int
    currentAge = 90
    
    println(maxAGE)
}

